#!/usr/bin/env bash
# Installing and configuring HAProxy as a load balancer for web-01 and web-02
apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << 'EOF'

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7175-web-01 3.86.237.61:80 check
    server 7175-web-02 3.95.161.238:80 check
EOF

service haproxy restart
