#!/usr/bin/env bash
#thi bash script post a file to the home directory of the server
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

if ["$#" -ne 4]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"

# Check if the SCP command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Failed to transfer file."
    exit 1
fi
