#!/usr/bin/env bash
# Creating a server with a redirect
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "
events {
}
http {
        server {
                listen 80 default_server;
                root /var/www/html;
                index index.html;
                location /redirect_me {
                        return 301 https://google.com;
                }
        }
}" > /etc/nginx/nginx.conf
nginx -t
service nginx restart
