#!/usr/bin/env bash
# Creating a server with a custom 404 page
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "
events {
}
http {
        server {
                listen 80 default_server;
                root /var/www/html;
                index index.html;
                error_page 404 /404.html;
                location /redirect_me {
                        return 301 https://google.com;
                }
        }
}" > /etc/nginx/nginx.conf
nginx -t
service nginx restart
